# Generated by Django 2.0.1 on 2018-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marketdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]
